{% set name = "sacremoses" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hplt-project/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 139faad4800a5da04498e4b5c297a5a8e1c958877b59090715d8a3f90e0b9b76

build:
  skip: true  # [py<38]
  number: 0
  entry_points:
    - sacremoses=sacremoses.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # While requirements.txt isn't applied, we'll loosely use those as guide for our
    # pinnings, since setup.py doesn't specify version ranges.
    - click >=7.1.2
    - joblib >=1.1.0
    - tqdm >=4.64.0
    - regex >=2020.1.8

test:
  source_files:
    - sacremoses/test
  imports:
    - sacremoses
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - sacremoses --help
    - pytest -vv sacremoses/test

about:
  home: https://github.com/hplt-project/sacremoses
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python port of Moses tokenizer, truecaser and normalizer
  description: Python port of Moses tokenizer, truecaser and normalizer
  dev_url: https://github.com/hplt-project/sacremoses
  doc_url: https://github.com/hplt-project/sacremoses

extra:
  recipe-maintainers:
    - roccqqck
