{% set name = "sacremoses" %}
{% set version = "0.0.41" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 964e9e2c06f26932707bbb2a2890263d222a8d43b1867f6b565ef6022d8f7676

build:
  noarch: python
  number: 0
  entry_points:
    - sacremoses=sacremoses.cli:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - click
    - joblib
    - python
    - regex
    - six
    - tqdm

test:
  imports:
    - sacremoses
  commands:
    - sacremoses --help

about:
  home: https://github.com/alvations/sacremoses
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: SacreMoses

extra:
  recipe-maintainers:
    - roccqqck
